image: docker:stable
services:
- docker:dind

stages:
- build
#- test
- release
#- deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/dispatcher:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/dispatcher:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.example.com

build:
  stage: build
  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    - docker push "$CONTAINER_TEST_IMAGE"
#
#test1:
#  stage: test
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests
#
#test2:
#  stage: test
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

release-image:
  stage: release
  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master
#
#deploy:
#  stage: deploy
#  script:
#    - ./deploy.sh
#  only:
#    - master